# Generated by Django 5.0.4 on 2024-04-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20)),
                ('cimg', models.ImageField(default='', upload_to='upload')),
            ],
            options={
                'db_table': 'addcource',
            },
        ),
    ]
