# Generated by Django 5.0.4 on 2024-04-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_addco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addco',
            name='cimg',
            field=models.ImageField(upload_to='upload'),
        ),
    ]
