# Generated by Django 5.0.4 on 2024-04-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_addco_cimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addcontent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=30)),
                ('contitle', models.CharField(max_length=50)),
                ('condes', models.CharField(max_length=5000)),
                ('conlink', models.CharField(max_length=30)),
                ('confile', models.FileField(upload_to='upload')),
            ],
            options={
                'db_table': 'addcontent',
            },
        ),
    ]
